### ISSUE TITLE
st2-pack-install fails on cloned pack that has been checked out to a branch

### ISSUE THREAD

**Issue by AndyMoore** [StackStorm/st2packs-dockerfiles#4]
this works - checked out master

```
Step 8/34 : RUN /usr/bin/st2-pack-install file:///packs/aws_efs
 ---> Running in 22cd6435982b
2018-09-27 22:47:23,908 INFO [-] Installing pack "file:///packs/aws_efs"
2018-09-27 22:47:25,808 INFO [-] Successfully installed pack "aws_efs"
2018-09-27 22:47:25,809 INFO [-] Setting up virtualenv for pack "aws_efs"
2018-09-27 22:47:25,810 INFO [-] Virtualenv path "/opt/stackstorm/virtualenvs/aws_efs" doesn't exist
2018-09-27 22:48:19,936 INFO [-] Successfully set up virtualenv for pack "aws_efs"
Removing intermediate container 22cd6435982b
```

This fails - checked out a branch

```
Step 9/34 : RUN /usr/bin/st2-pack-install file:///packs/consul
 ---> Running in 089d41bf34d7
2018-09-27 22:48:24,542 INFO [-] Installing pack "file:///packs/consul"
Traceback (most recent call last):
  File "/usr/bin/st2-pack-install", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/src/st2common/st2common/bin/st2-pack-install", line 42, in <module>
    sys.exit(install_pack.main(sys.argv[1:]))
  File "/src/st2common/st2common/st2common/cmd/install_pack.py", line 66, in main
    proxy_config=proxy_config, force_permissions=True)
  File "/src/st2common/st2common/st2common/util/pack_management.py", line 119, in download_pack
    ref=pack_version)
  File "/src/st2common/st2common/st2common/util/pack_management.py", line 154, in clone_repo
    active_branch = repo.active_branch
  File "/usr/lib/python2.7/site-packages/git/repo/base.py", line 696, in active_branch
    return self.head.reference
  File "/usr/lib/python2.7/site-packages/git/refs/symbolic.py", line 275, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to '96ccf2ec68fd52680bade668ccced67c4a77e102'
ERROR: Service 'image-st2pack' failed to build: The command '/bin/sh -c /usr/bin/st2-pack-install file:///packs/consul' returned a non-zero code: 1
```

**Comment by Kami** [comment]
@AndyMoore Can you please share a link to the git repo for a pack you are having issue with and which branch?

I can't reproduce it locally, I tried using multiple pack git repos and different branches.

```bash
vagrant@ubuntu-xenial:/data/stanley/stackstorm-consul$ git branch
  master
* nzlosh-patch-1
vagrant@ubuntu-xenial:/data/stanley/stackstorm-consul$ cd ..
vagrant@ubuntu-xenial:/data/stanley$ st2common/bin/st2-pack-install file:////data/stanley/stackstorm-consul/
2018-09-28 07:52:14,755 INFO [-] Installing pack "file:////data/stanley/stackstorm-consul/"
2018-09-28 07:52:14,850 INFO [-] Successfully installed pack "consul"
2018-09-28 07:52:14,851 INFO [-] Setting up virtualenv for pack "consul"
2018-09-28 07:52:14,854 INFO [-] Virtualenv path "/opt/stackstorm/virtualenvs/consul" doesn't exist
2018-09-28 07:52:18,209 INFO [-] Successfully set up virtualenv for pack "consul"
```

As you can see, I also tried to reproduce it using consul pack from StackStorm Exchange with a non-master branch checked out and it worked fine.

I wonder if it's related to some other edge case - like shallow clone or specific commit being checked out.

**Comment by Kami** [comment]
I managed to reproduce it - it only happens when repo is in a detached head state aka specific commit is checked out.

I pushed a change so we now also support this use case - https://github.com/StackStorm/st2/pull/4366. 

```bash
(virtualenv) vagrant@ubuntu-xenial:/data/stanley$ st2common/bin/st2-pack-install "file:////data/stanley/stackstorm-consul/" 
2018-09-28 08:11:14,211 INFO [-] Installing pack "file:////data/stanley/stackstorm-consul/"
2018-09-28 08:11:14,303 INFO [-] Successfully installed pack "consul"
2018-09-28 08:11:14,303 INFO [-] Setting up virtualenv for pack "consul"
2018-09-28 08:11:17,743 INFO [-] Successfully set up virtualenv for pack "consul"
```

Having said that, I think it's usually better to check out a specific version tag / branch compared to checking out a specific commit.
